// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    scenario_tester
    (
        init => init
        upgrade => upgrade
        getSum => sum
        getOtherMapper => other_mapper
        add => add
        set_other_mapper => set_other_mapper
        multi_param => multi_param
        multi_return => multi_return
        sc_panic => sc_panic
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
