version: "3.9"

services:
 chain-simulator:
  image: dharitri/chainsimulator:latest
  ports:
    - 8085:8085
  volumes:
    - "../scripts:/docker/scripts"
  entrypoint: "./chainsimulator -log-level *:INFO"