// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           21
// Async Callback (empty):               1
// Total number of exported functions:  23

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    payable_features
    (
        init => init
        payable_legacy_rewa_dcdt => payable_legacy_rewa_dcdt
        payment_multiple => payment_multiple
        payable_all_transfers => payable_all_transfers
        payable_all => payable_all
        payment_array_dcdt_3 => payment_array_dcdt_3
        payment_array_rewa_or_dcdt_3 => payment_array_rewa_or_dcdt_3
        payment_array_3 => payment_array_3
        payable_any_1 => payable_any_1
        payable_any_2 => payable_any_2
        payable_any_3 => payable_any_3
        payable_any_4 => payable_any_4
        payable_any_5 => payable_any_5
        payable_rewa_1 => payable_rewa_1
        payable_rewa_2 => payable_rewa_2
        payable_rewa_3 => payable_rewa_3
        payable_rewa_4 => payable_rewa_4
        payable_rewa_5 => payable_rewa_5
        payable_token_1 => payable_token_1
        payable_token_2 => payable_token_2
        payable_token_3 => payable_token_3
        payable_token_4 => payable_token_4
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
