[package]
name = "ping-pong-moa-interact"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[[bin]]
name = "ping-pong-moa-interact"
path = "src/interact_main.rs"

[lib]
path = "src/interact.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.6"
tokio = { version = "1.24" }

[dependencies.ping-pong-moa]
path = ".."

[dependencies.dharitri-sc-snippets]
version = "0.55.0"
path = "../../../../framework/snippets"

[features]
chain-simulator-tests = []
