[package]
name = "dharitri-sc-wmoa-swap-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.dharitri-sc-wmoa-swap]
path = ".."

[dependencies.dharitri-sc]
version = "0.55.0"
path = "../../../../framework/base"

[dependencies.dharitri-sc-meta-lib]
version = "0.55.0"
path = "../../../../framework/meta-lib"
default-features = false
