// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            0
// Async Callback (empty):               1
// Total number of exported functions:   3

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler_std!();

dharitri_sc_wasm_adapter::endpoints! {
    std_contract
    (
        init => init
        upgrade => upgrade
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
