// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    barnard_features
    (
        init => init
        epochInfo => epoch_info
        codeHash => code_hash
        get_block_timestamps => get_block_timestamps
        get_block_timestamp_ms => get_block_timestamp_ms
        get_prev_block_timestamp_ms => get_prev_block_timestamp_ms
        get_dcdt_token_data => get_dcdt_token_data
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
